# Generated by Django 3.1.6 on 2021-06-22 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210508_1710'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filament',
            name='help_link',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.region'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
