# Generated by Django 3.1.6 on 2021-06-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210622_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='filament',
            name='type',
            field=models.CharField(choices=[('Refill+Spool', 'Refill+Spool'), ('Refill', 'Refill'), ('Full Spool', 'Full Spool')], default='Refill+Spool', max_length=20),
        ),
    ]
