# Generated by Django 3.1.6 on 2021-07-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_filament_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filament',
            name='EAN',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='filament',
            name='SKU',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
