"""
Django settings for Cubic3D project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import posixpath
from sys import platform

# Detect local development environment (Windows or macOS)
IS_LOCAL = platform in ('win32', 'darwin')

# Load .env file automatically when running locally.
# Create a .env file in the project root with your local secrets (never commit it).
if IS_LOCAL:
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass  # Install python-dotenv: pip install python-dotenv


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

#ADMINS = [('Tony','abbrowna@cubic3d.co.ke')]
#LOGGING = {
#    'handlers': {
#        'mail_admins': {
#            'level': 'ERROR',
#            'class': 'django.utils.log.AdminEmailHandler',
#            'include_html': True,
#            'email_backend': 'django.core.mail.backends.filebased.EmailBackend',
#        },
#    },
#}

# SECURITY WARNING: keep the secret key used in production secret!
# Production: env vars are declared in the uwsgi config file.
# Local dev: set these in a .env file in the project root.
SECRET_KEY = os.environ.get('SECRET_KEY', 'local-dev-insecure-key-do-not-use-in-production')
RECAPTCHA_PUBLIC_KEY = os.environ.get('CAPTCHA_PUBLIC_KEY', 'dummy')
RECAPTCHA_PRIVATE_KEY = os.environ.get('CAPTCHA_PRIVATE_KEY', 'dummy')
RECAPTCHA_REQUIRED_SCORE = 0.85
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = IS_LOCAL
#HOLIDAY MODE adds an overlay with a message above the create print request page preventing users from making print requests 
HOLIDAY_MODE = False


ALLOWED_HOSTS = ['146.190.104.24','139.59.26.37','188.166.237.15','localhost','127.0.0.1','cubic3d.co.ke','www.cubic3d.co.ke','store.cubic3d.co.ke','www.store.cubic3d.co.ke']

# Application definition
INSTALLED_APPS = [
    
    # Add your apps here to enable them
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'store',
    'app',
    'verify_email',
    'django_recaptcha',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'whitenoise.middleware.WhiteNoiseMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'
ROOT_URLCONF = 'Cubic3D.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'Cubic3D.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

if IS_LOCAL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join('/home/cubic/web', 'db.sqlite3'),
        }
    }

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = 'login'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = posixpath.join(*(BASE_DIR.split(os.path.sep) + ['static']))
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

#File system and static files

MEDIA_URL = '/media/'
if IS_LOCAL:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
else:
    MEDIA_ROOT = os.path.join('/home/cubic', 'media/')


#Email
if IS_LOCAL:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_HOST = 'smtp.zoho.com'
    EMAIL_PORT = 587
    EMAIL_HOST_USER = 'orders@cubic3d.co.ke'
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS', '')
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = 'Cubic3D Account<orders@cubic3d.co.ke>'

#Templates for email verification
HTML_MESSAGE_TEMPLATE = os.path.join(BASE_DIR, 'app/templates/email/verification_email.html')
VERIFICATION_SUCCESS_TEMPLATE = os.path.join(BASE_DIR, 'app/templates/registration/verification_success.html')
VERIFICATION_FAILED_TEMPLATE = os.path.join(BASE_DIR, 'app/templates/registration/verification_failed.html')

# Security / HSTS (production only)
if not IS_LOCAL:
    SECURE_HSTS_SECONDS = 31536000          # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = False             # nginx handles redirect
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
