# Generated by Django 2.1 on 2018-08-22 10:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default=0, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.FileField(upload_to='thingstemp/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['stl'], 'Please export your file as a .STL object then upload it. If your unable, Email your file to us instead')])),
                ('material', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG')], default='PLA', max_length=5)),
                ('purpose', models.CharField(choices=[('ART', 'Artistic/Aestetic'), ('MECH', 'Mechanical')], default='ART', max_length=5)),
                ('color', models.CharField(choices=[('GRN', 'Green'), ('BLK', 'Black'), ('GRY', 'Grey'), ('BLUE', 'Blue'), ('RED', 'Red'), ('WHT', 'White'), ('COMBO', 'Combination')], default='GRN', max_length=10)),
                ('scale', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tempthings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descriptive name')),
                ('thing', models.FileField(upload_to='thingstemp/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['stl'], 'Please upload your file as a .STL Most CAD software are capable of exporting models in this format.')])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG')], default='PLA', max_length=5)),
                ('purpose', models.CharField(choices=[('ART', 'Artistic/Aestetic'), ('MECH', 'Mechanical')], default='ART', max_length=5)),
                ('color', models.CharField(choices=[('GRN', 'Green'), ('BLK', 'Black'), ('GRY', 'Grey'), ('BLUE', 'Blue'), ('RED', 'Red'), ('WHT', 'White'), ('COMBO', 'Color combo')], default='GRN', max_length=10)),
                ('color_combo', models.TextField(blank=True)),
                ('scale', models.FloatField(default=100)),
                ('further_requests', models.TextField(blank=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThingOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descriptive name')),
                ('thing', models.FileField(upload_to='orderedthings/%Y/%m/%d/')),
                ('confirmed_on', models.DateTimeField(auto_now_add=True)),
                ('material', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG')], default='PLA', max_length=5)),
                ('purpose', models.CharField(choices=[('ART', 'Artistic/Aestetic'), ('MECH', 'Mechanical')], default='ART', max_length=5)),
                ('color', models.CharField(choices=[('GRN', 'Green'), ('BLK', 'Black'), ('GRY', 'Grey'), ('BLUE', 'Blue'), ('RED', 'Red'), ('WHT', 'White'), ('COMBO', 'Combination')], default='GRN', max_length=10)),
                ('color_combo', models.TextField(blank=True)),
                ('scale', models.FloatField(default=False)),
                ('further_requests', models.TextField(blank=True)),
                ('printed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
