# Generated by Django 6.0.6 on 2026-06-18 09:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRecord',
            fields=[
                ('id_string', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('acronym', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Material Acronym')),
                ('full_name', models.CharField(blank=True, max_length=50, verbose_name='Full name')),
                ('density', models.FloatField()),
                ('ppg', models.IntegerField(verbose_name='Price per gram')),
                ('color1', models.CharField(blank=True, max_length=15)),
                ('color2', models.CharField(blank=True, max_length=15)),
                ('color3', models.CharField(blank=True, max_length=15)),
                ('color4', models.CharField(blank=True, max_length=15)),
                ('color5', models.CharField(blank=True, max_length=15)),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Card tagline (short phrase shown when card is clicked)')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('bill_to', models.CharField(blank=True, max_length=100)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descriptive name')),
                ('thing', models.FileField(upload_to='thingstemp/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['stl'], 'Please upload your file as a .STL Most CAD software are capable of exporting models in this format.')])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(choices=[('ART', 'Artistic/Aestetic'), ('MECH', 'Mechanical')], default='ART', max_length=5)),
                ('color', models.CharField(max_length=15)),
                ('color_combo', models.TextField(blank=True)),
                ('scale', models.FloatField(default=100)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('further_requests', models.TextField(blank=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('grouped', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('final_price', models.IntegerField(blank=True, null=True)),
                ('printed', models.BooleanField(default=False)),
                ('receipted', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(default='PLA', on_delete=django.db.models.deletion.CASCADE, to='app.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupedPrintRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.printrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.FileField(upload_to='thingstemp/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['stl'], 'Please upload your file as a .STL Most CAD software are capable of exporting models in this format.')])),
                ('purpose', models.CharField(choices=[('ART', 'Artistic/Aestetic'), ('MECH', 'Mechanical')], default='ART', max_length=5)),
                ('color', models.CharField(max_length=15)),
                ('scale', models.FloatField(default=100)),
                ('material', models.ForeignKey(default='PLA', on_delete=django.db.models.deletion.CASCADE, to='app.material')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default=0, max_length=10)),
                ('address', models.TextField(max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.region')),
            ],
        ),
        migrations.CreateModel(
            name='ThingOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descriptive name')),
                ('thing', models.FileField(upload_to='orderedthings/%Y/%m/%d/')),
                ('confirmed_on', models.DateTimeField(auto_now_add=True)),
                ('material', models.CharField(max_length=5)),
                ('purpose', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=15)),
                ('color_combo', models.TextField(blank=True)),
                ('scale', models.FloatField(default=False)),
                ('further_requests', models.TextField(blank=True)),
                ('printed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
