# Generated by Django 2.1.2 on 2018-10-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('acronym', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Material Acronym')),
                ('color1', models.CharField(blank=True, max_length=5)),
                ('color2', models.CharField(blank=True, max_length=5)),
                ('color3', models.CharField(blank=True, max_length=5)),
                ('color4', models.CharField(blank=True, max_length=5)),
                ('color5', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
