# Generated by Django 2.1.2 on 2018-10-12 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempthings',
            name='color',
            field=models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG')], default='GRN', max_length=10),
        ),
        migrations.AlterField(
            model_name='tempthings',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Material'),
        ),
    ]
