# Generated by Django 2.1.2 on 2018-10-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181012_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempthings',
            name='color',
            field=models.CharField(choices=[('GRN', 'Green'), ('BLK', 'Black'), ('GRY', 'Grey'), ('BLUE', 'Blue'), ('RED', 'Red'), ('WHT', 'White'), ('COMBO', 'Color combo')], default='GRN', max_length=10),
        ),
    ]
