# Generated by Django 2.1.2 on 2018-10-13 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181012_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempthings',
            name='color',
            field=models.CharField(default='White', max_length=10),
        ),
        migrations.AlterField(
            model_name='tempthings',
            name='material',
            field=models.ForeignKey(default='PLA', on_delete=django.db.models.deletion.CASCADE, to='app.Material'),
        ),
    ]
