# Generated by Django 2.1.2 on 2018-10-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181013_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='density',
            field=models.FloatField(default=1.75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tempthings',
            name='color',
            field=models.CharField(max_length=10),
        ),
    ]
