# Generated by Django 2.1.2 on 2018-10-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181014_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='ppg',
            field=models.IntegerField(default=15, verbose_name='Price per gram'),
            preserve_default=False,
        ),
    ]
