# Generated by Django 2.1.2 on 2018-11-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181102_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingorders',
            name='color',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='thingorders',
            name='material',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='thingorders',
            name='purpose',
            field=models.CharField(max_length=5),
        ),
    ]
