# Generated by Django 2.1.2 on 2018-11-14 07:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20181106_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descriptive name')),
                ('thing', models.FileField(upload_to='thingstemp/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['stl'], 'Please upload your file as a .STL Most CAD software are capable of exporting models in this format.')])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(choices=[('ART', 'Artistic/Aestetic'), ('MECH', 'Mechanical')], default='ART', max_length=5)),
                ('color', models.CharField(max_length=10)),
                ('color_combo', models.TextField(blank=True)),
                ('scale', models.FloatField(default=100)),
                ('further_requests', models.TextField(blank=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmation_date', models.DateTimeField()),
                ('final_price', models.IntegerField(null=True)),
                ('printed', models.BooleanField(default=False)),
                ('material', models.ForeignKey(default='PLA', on_delete=django.db.models.deletion.CASCADE, to='app.Material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tempthings',
            name='material',
        ),
        migrations.RemoveField(
            model_name='tempthings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tempthings',
        ),
    ]
