# Generated by Django 2.1.2 on 2018-11-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181114_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printrequest',
            name='confirmation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
