# Generated by Django 2.1.2 on 2018-11-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181114_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printrequest',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printrequest',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
