# Generated by Django 2.1.2 on 2018-11-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181114_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupedPrintRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PrintRequest')),
            ],
        ),
    ]
