# Generated by Django 2.1.2 on 2018-11-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_groupedprintrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='printrequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
