# Generated by Django 2.1.2 on 2018-11-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_printrequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='printrequest',
            name='grouped',
            field=models.BooleanField(default=False),
        ),
    ]
