# Generated by Django 2.1.2 on 2018-11-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_printrequest_receipted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printrequest',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
