# Generated by Django 2.2.17 on 2021-01-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210118_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
