# Generated by Django 2.2.17 on 2021-01-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_invoice_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='printrequest',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
